version = 0.1

# Development Environment
[dev.deploy.parameters]
stack_name = "[***PROJECT_NAME***]-dev"
resolve_s3 = true
s3_prefix = "[***PROJECT_NAME***]-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=dev"
]

# Production Environment  
[prod.deploy.parameters]
stack_name = "[***PROJECT_NAME***]-prod"
resolve_s3 = true
s3_prefix = "[***PROJECT_NAME***]-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=prod"
]

# Keep default as prod for backward compatibility
[default.deploy.parameters]
stack_name = "[***PROJECT_NAME***]"
resolve_s3 = true
s3_prefix = "[***PROJECT_NAME***]"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []