version = 0.1

# Development Environment
[dev.deploy.parameters]
stack_name = "house-mgmt-dev"
resolve_s3 = true
s3_prefix = "house-mgmt-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=\"dev\" AllowedIPs=\"0.0.0.0/0\""

# Production Environment  
[prod.deploy.parameters]
stack_name = "house-mgmt-prod"
resolve_s3 = true
s3_prefix = "house-mgmt-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=prod",
    "AllowedIPs=$PRODUCTION_ALLOWED_IPS"  # Will be set by GitHub Actions
]

# Default to dev for local development
[default.deploy.parameters]
stack_name = "house-mgmt-dev"
resolve_s3 = true
s3_prefix = "house-mgmt-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Environment=dev",
    "AllowedIPs=0.0.0.0/0"
]